// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wG2755SB0xm4DexGBbi8c64nGKgCXnI',
    appId: '1:669819490274:web:a9f23dce1f8e584d7e33bb',
    messagingSenderId: '669819490274',
    projectId: 'basv2-9c201',
    authDomain: 'basv2-9c201.firebaseapp.com',
    storageBucket: 'basv2-9c201.firebasestorage.app',
    measurementId: 'G-BYCESNQLCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHd1LqktlNXttzHnEiUaxXR_qb3p2ebgE',
    appId: '1:669819490274:android:d7a18aafe1542ffc7e33bb',
    messagingSenderId: '669819490274',
    projectId: 'basv2-9c201',
    storageBucket: 'basv2-9c201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbP6J5BEsQbytmZ5GXusERDjTypBF7-c',
    appId: '1:669819490274:ios:e48d18c2376107837e33bb',
    messagingSenderId: '669819490274',
    projectId: 'basv2-9c201',
    storageBucket: 'basv2-9c201.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbP6J5BEsQbytmZ5GXusERDjTypBF7-c',
    appId: '1:669819490274:ios:e48d18c2376107837e33bb',
    messagingSenderId: '669819490274',
    projectId: 'basv2-9c201',
    storageBucket: 'basv2-9c201.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wG2755SB0xm4DexGBbi8c64nGKgCXnI',
    appId: '1:669819490274:web:c1627791c01c79b77e33bb',
    messagingSenderId: '669819490274',
    projectId: 'basv2-9c201',
    authDomain: 'basv2-9c201.firebaseapp.com',
    storageBucket: 'basv2-9c201.firebasestorage.app',
    measurementId: 'G-P05395QNMD',
  );
}
